version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:8080
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    ports:
      - 8000:8000
    depends_on:
      - db
