version: '3.1'
services:
  db:
    image: academy.azurecr.io/samples/dev-academy-db:latest
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "academy", "-d", "electricity"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: academy.azurecr.io/samples/dev-academy-backend:latest
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: electricity
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    image: academy.azurecr.io/samples/dev-academy-frontend:latest
    environment:
      VITE_API_BASE_URL: http://dev-academy.westeurope.cloudapp.azure.com
    ports:
      - 80:80
    depends_on:
      - backend
    

