name: pipeline
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker compose
        uses: docker/setup-compose-action@v1
      
      - name: Compose build
        run: docker compose --file docker-compose.prod.yml build
      
      - name: Compose up
        run: docker compose --file docker-compose.prod.yml up --renew-anon-volumes -d

      - name: Wait 10 seconds
        run: sleep 10

      - name: Run tests
        run: docker exec $(docker ps -q --filter name=dev-academy-spring-2025-exercise-backend-1) pytest

      - name: Compose down
        run: docker compose --file docker-compose.prod.yml down

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login and push images'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker tag dev-academy-spring-2025-exercise-backend:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/dev-academy-spring-2025-exercise-backend:${{ github.sha }}
          docker tag dev-academy-spring-2025-exercise-frontend:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/dev-academy-spring-2025-exercise-frontend:${{ github.sha }}
          docker tag dev-academy-spring-2025-exercise-db:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/dev-academy-spring-2025-exercise-db:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dev-academy-spring-2025-exercise-backend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dev-academy-spring-2025-exercise-frontend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/dev-academy-spring-2025-exercise-db:${{ github.sha }}
