name: pipeline
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker compose
        uses: docker/setup-compose-action@v1
      
      - name: Compose build
        run: docker compose --file docker-compose.prod.yml build
      
      - name: Compose up
        run: docker compose --file docker-compose.prod.yml up --renew-anon-volumes -d

      - name: Wait 10 seconds
        run: sleep 10

      - name: log docker ps
        run: docker ps 

      - name: log docker ps filter
        run: docker ps -q --filter name=dev-academy-backend-1

      - name: Run tests
        run: docker exec $(docker ps -q --filter name=dev-academy-backend-1) pytest

      - name: Compose down
        run: docker compose --file docker-compose.prod.yml down

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure container registry login
        run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

      - name: push backend image
        run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/samples/dev-academy-backend:latest
      
      - name: push frontend image
        run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/samples/dev-academy-frontend:latest

      - name: push db image
        run: docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/samples/dev-academy-db:latest
